// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generated_code.proto

module generated_code;

import google.protobuf;

class TestMessage
{
    @Proto(1) int optionalInt32 = defaultValue!(int);
    @Proto(2) long optionalInt64 = defaultValue!(long);
    @Proto(3) uint optionalUint32 = defaultValue!(uint);
    @Proto(4) ulong optionalUint64 = defaultValue!(ulong);
    @Proto(5) bool optionalBool = defaultValue!(bool);
    @Proto(6) double optionalDouble = defaultValue!(double);
    @Proto(7) float optionalFloat = defaultValue!(float);
    @Proto(8) string optionalString = defaultValue!(string);
    @Proto(9) bytes optionalBytes = defaultValue!(bytes);
    @Proto(10) TestEnum optionalEnum = defaultValue!(TestEnum);
    @Proto(11) TestMessage optionalMsg = defaultValue!(TestMessage);
    @Proto(21) int[] repeatedInt32 = defaultValue!(int[]);
    @Proto(22) long[] repeatedInt64 = defaultValue!(long[]);
    @Proto(23) uint[] repeatedUint32 = defaultValue!(uint[]);
    @Proto(24) ulong[] repeatedUint64 = defaultValue!(ulong[]);
    @Proto(25) bool[] repeatedBool = defaultValue!(bool[]);
    @Proto(26) double[] repeatedDouble = defaultValue!(double[]);
    @Proto(27) float[] repeatedFloat = defaultValue!(float[]);
    @Proto(28) string[] repeatedString = defaultValue!(string[]);
    @Proto(29) bytes[] repeatedBytes = defaultValue!(bytes[]);
    @Proto(30) TestEnum[] repeatedEnum = defaultValue!(TestEnum[]);
    @Proto(31) TestMessage[] repeatedMsg = defaultValue!(TestMessage[]);
    enum MyOneofCase
    {
        myOneofNotSet = 0,
        oneofInt32 = 41,
        oneofInt64 = 42,
        oneofUint32 = 43,
        oneofUint64 = 44,
        oneofBool = 45,
        oneofDouble = 46,
        oneofFloat = 47,
        oneofString = 48,
        oneofBytes = 49,
        oneofEnum = 50,
        oneofMsg = 51,
    }
    MyOneofCase _myOneofCase = MyOneofCase.myOneofNotSet;
    @property MyOneofCase myOneofCase() { return _myOneofCase; }
    void clearMyOneof() { _myOneofCase = MyOneofCase.myOneofNotSet; }
    @Oneof("_myOneofCase") union
    {
        @Proto(41) int _oneofInt32 = defaultValue!(int); mixin(oneofAccessors!_oneofInt32);
        @Proto(42) long _oneofInt64; mixin(oneofAccessors!_oneofInt64);
        @Proto(43) uint _oneofUint32; mixin(oneofAccessors!_oneofUint32);
        @Proto(44) ulong _oneofUint64; mixin(oneofAccessors!_oneofUint64);
        @Proto(45) bool _oneofBool; mixin(oneofAccessors!_oneofBool);
        @Proto(46) double _oneofDouble; mixin(oneofAccessors!_oneofDouble);
        @Proto(47) float _oneofFloat; mixin(oneofAccessors!_oneofFloat);
        @Proto(48) string _oneofString; mixin(oneofAccessors!_oneofString);
        @Proto(49) bytes _oneofBytes; mixin(oneofAccessors!_oneofBytes);
        @Proto(50) TestEnum _oneofEnum; mixin(oneofAccessors!_oneofEnum);
        @Proto(51) TestMessage _oneofMsg; mixin(oneofAccessors!_oneofMsg);
    }
    @Proto(61) string[int] mapInt32String = defaultValue!(string[int]);
    @Proto(62) string[long] mapInt64String = defaultValue!(string[long]);
    @Proto(63) string[uint] mapUint32String = defaultValue!(string[uint]);
    @Proto(64) string[ulong] mapUint64String = defaultValue!(string[ulong]);
    @Proto(65) string[bool] mapBoolString = defaultValue!(string[bool]);
    @Proto(66) string[string] mapStringString = defaultValue!(string[string]);
    @Proto(67) TestMessage[string] mapStringMsg = defaultValue!(TestMessage[string]);
    @Proto(68) TestEnum[string] mapStringEnum = defaultValue!(TestEnum[string]);
    @Proto(69) int[string] mapStringInt32 = defaultValue!(int[string]);
    @Proto(70) bool[string] mapStringBool = defaultValue!(bool[string]);
    @Proto(80) NestedMessage nestedMessage = defaultValue!(NestedMessage);

    static class NestedMessage
    {
        @Proto(1) int foo = defaultValue!(int);
    }
}

enum TestEnum
{
    Default = 0,
    A = 1,
    B = 2,
    C = 3,
}
