// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/any.proto
module google.protobuf.any;

import google.protobuf;

class Any
{
    @Proto(1) string typeUrl = defaultValue!(string);
    @Proto(2) bytes value = defaultValue!(bytes);
}
