// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/field_mask.proto
module google.protobuf.field_mask;

import google.protobuf;

class FieldMask
{
    @Proto(1) string[] paths = defaultValue!(string[]);
}
