// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/struct.proto
module google.protobuf.struct_;

import google.protobuf;

class Struct
{
    @Proto(1) Value[string] fields = defaultValue!(Value[string]);
}

class Value
{
    enum KindCase
    {
        caseKindNotSet = 0,
        caseNullValue = 1,
        caseNumberValue = 2,
        caseStringValue = 3,
        caseBoolValue = 4,
        caseStructValue = 5,
        caseListValue = 6,
    }
    KindCase _kindCase = KindCase.caseKindNotSet;
    @property KindCase kindCase() { return _kindCase; }
    void clearKind() { _kindCase = KindCase.caseKindNotSet; }
    @Oneof("_kindCase") union
    {
        @Proto(1) NullValue _nullValue = defaultValue!(NullValue); mixin(oneofAccessors!_nullValue);
        @Proto(2) double _numberValue; mixin(oneofAccessors!_numberValue);
        @Proto(3) string _stringValue; mixin(oneofAccessors!_stringValue);
        @Proto(4) bool _boolValue; mixin(oneofAccessors!_boolValue);
        @Proto(5) Struct _structValue; mixin(oneofAccessors!_structValue);
        @Proto(6) ListValue _listValue; mixin(oneofAccessors!_listValue);
    }
}

class ListValue
{
    @Proto(1) Value[] values = defaultValue!(Value[]);
}

enum NullValue
{
    NULL_VALUE = 0,
}
